AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Outputs:
  ElasticLoadBalancerDNSnimi:
    Description: JennanLoadBalancerinDNS
    Value: !GetAtt JennanLoadBalancerV2.DNSName

Resources:
  JennanS3Ampari:
    Type: AWS::S3::Bucket

  JennanJono:
    Type: AWS::SQS::Queue

  JennanEC2masiina:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref JennanEC2SecurityGroup

  JennanLoadBalancerV2:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - subnet-3bfa1864
        - subnet-7a917d5b
      SecurityGroups:
        - !Ref JennanLoadBalancerV2SecurityGroup


  JennanEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: jennanEC2securityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref JennanLoadBalancerV2SecurityGroup

  JennanLoadBalancerV2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: jennanLoadBalancersecurityGroup
      VpcId: vpc-bcd4e6c6





