AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Outputs:
  ElasticLoadBalancerDNSnimi:
    Description: JennanLoadBalancerinDNS
    Value: !GetAtt JennanLoadBalancer.DNSName

Resources:
  JennanS3Ampari:
    Type: AWS::S3::Bucket

  JennanJono:
    Type: AWS::SQS::Queue

  JennanEC2masiina:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref JennanEC2SecurityGroup

  JennanLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
      - "us-east-1a"
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      SecurityGroups:
        - !Ref JennanLoadBalancerSecurityGroup
      Instances:
        - !Ref JennanEC2masiina

  JennanEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: jennanEC2securityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref JennanLoadBalancerSecurityGroup

  JennanLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: jennanLoadBalancersecurityGroup
      VpcId: vpc-bcd4e6c6




